services:
  db:
    image: postgres:16.2-alpine
    volumes:
      # Mantém os dados do PostgreSQL persistentes.
      - postgres_data:/var/lib/postgresql/data
      # Executa um script SQL na inicialização do banco para criar esquemas ou dados iniciais.
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    environment:
      # Variáveis de ambiente que o PostgreSQL usa para configurar o banco de dados inicial.
      POSTGRES_DB: weather_db # <-- Nome do banco de dados atualizado
      POSTGRES_USER: weather_user # <-- Usuário do banco de dados atualizado
      POSTGRES_PASSWORD: weather_pass # <-- Senha do banco de dados atualizada
    ports:
      # Mapeia a porta 5432 do contêiner para a porta 5432 na sua máquina local.
      - '5432:5432'
    restart: always # Garante que o contêiner reinicie se parar.
    healthcheck:
      # Verifica se o banco de dados está pronto para aceitar conexões.
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s # Dá um tempo inicial para o banco subir.

  app:
    build: . # Constrói a imagem Docker a partir do Dockerfile no diretório atual.
    ports:
      # Mapeia a porta 8000 do contêiner (onde o Django roda) para a porta 8000 na sua máquina local.
      - '8000:8000'
    environment:
      # Variáveis de ambiente para o Django se conectar ao PostgreSQL.
      # Elas são carregadas a partir do seu arquivo .env via python-decouple.
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db # 'db' é o nome do serviço do banco de dados no docker-compose.
      POSTGRES_PORT: 5432
    depends_on:
      # Garante que o serviço 'app' só inicie depois que 'db' estiver saudável.
      db:
        condition: service_healthy
    restart: always # Garante que o contêiner reinicie se parar.
    volumes:
      # Monta o diretório do seu projeto local para /app dentro do contêiner.
      # Isso permite que as alterações no seu código sejam refletidas sem reconstruir a imagem.
      - .:/app

volumes:
  # Define um volume nomeado para persistir os dados do PostgreSQL.
  postgres_data:
