# Generated by Django 4.2.1 on 2025-06-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherLoadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255)),
                ('log_level', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('event_name', models.CharField(blank=True, max_length=255, null=True)),
                ('event_location', models.CharField(blank=True, max_length=255, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('data_imported_count', models.IntegerField(default=0)),
                ('loaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255)),
                ('event_name', models.CharField(max_length=255)),
                ('event_location', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feels_like', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weather_main', models.CharField(blank=True, max_length=100, null=True)),
                ('weather_description', models.CharField(blank=True, max_length=255, null=True)),
                ('api_source', models.CharField(max_length=100)),
                ('load_version', models.IntegerField(default=1)),
                ('loaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['event_id', 'event_date', 'load_version'],
                'unique_together': {('event_id', 'event_location', 'event_date', 'load_version')},
            },
        ),
    ]
